7 create about page
diverintech/diverintech.github.io pull request #11
Opened 2024-12-16 15:22 UTC by diverintech

2024-12-16 17:45 UTC, fc46581 commented on src/app/pages/about/about.component.scss
A animação das frases está a parar na terceira e depois começa do inicio

2024-12-16 17:53 UTC, fc46581 requested changes
Muito giro! Adicionei duas coisas que podes alterar

2024-12-16 17:53 UTC, fc46581 commented on src/assets/i18n/pt.json
As últimas duas quotes soam muito a Português do Brasil.
Muda antes para:

"QUOTE_2": "A vida é como andar de bicicleta. Para manter o equilíbrio, é preciso continuar em movimento. — Albert Einstein",
"QUOTE_3": "O futuro pertence àqueles que acreditam na beleza dos seus sonhos. — Eleanor Roosevelt"

2024-12-16 18:03 UTC, RodrasSilva commented on package-lock.json
**Questão**: Este ficheiro não pode ser adicionado ao `.gitignore`? Ele é gerado a partir do `package.json`, por isso é possível gerar na própria máquina.

2024-12-16 18:03 UTC, RodrasSilva commented on src/app/app.config.ts
> +import { provideAnimationsAsync } from '@angular/platform-browser/animations/async'
**Melhoria**: Ser coerente na forma de importar dependências/componentes
```suggestion
import { provideAnimationsAsync } from '@angular/platform-browser/animations/async';
```

2024-12-16 18:03 UTC, RodrasSilva commented on src/app/app.config.ts
> +    ), provideAnimationsAsync(),
Melhoria, não terminar com virgulas no último elemento
```suggestion
    ), provideAnimationsAsync()
```

2024-12-16 18:03 UTC, RodrasSilva commented on src/app/dialog/math-quiz/math-quiz.component.ts
> +  public userAnswer!: number | null; // Stores the user's answer; allows null for resetting the input field.
**Questão**: O que faz o operador `!` depois do nome da variável?

2024-12-16 19:54 UTC, SofjaIRM commented on package-lock.json
@RodrasSilva Eu não adicionaria ao `.gitignore` uma vez que o `package-lock.json` permite guardar todas as referências exatas dos pacotes que dependem uns dos outros e na hora de corrigir vulnerabilidades por exemplo, vai permitir que todos os envolvidos no projeto tenham exatamente as mesmas versões dos pacotes.

2024-12-16 21:13 UTC, RodrasSilva commented on package-lock.json
@SofjaIRM o `package-lock.json` é gerado através de um processo de compilação / construção do projeto. Não é boa pratica incluir especialmente quando as versões presentes no `package.json` não são fixas, são variáveis. 
As ferramentas que analise estática que são usadas para detetar vulnerabilidade utilizam o `package-lock.json` gerado em cada processo de build (numa pipeline por exemplo) para aferir se o projeto tem vulnerabilidades, por isso não há necessidade de incluir no repositório.

2024-12-17 15:27 UTC, fc46581 approved these changes

2024-12-17 15:38 UTC, diverintech commented on package-lock.json
@RodrasSilva  Em nenhum dos projetos em que trabalhei até agora tínhamos o package-lock.json adicionado ao .gitignore, por isso nunca considerei essa possibilidade. No entanto, ao fazer uma pesquisa rápida sobre o assunto, encontrei esta pergunta no Stack Overflow: [Should the package-lock.json file be added to gitignore?](https://stackoverflow.com/questions/48524417/should-the-package-lock-json-file-be-added-to-gitignore).

Lá, mencionam que ao remover o package-lock.json, o comando npm ci apresenta um erro, uma vez que a sua existência é obrigatória. Como vou adicionar algumas actions ao projeto que vão necessitar de correr npm ci, é essencial manter o ficheiro no repositório.

"npm ci requires the existence of a package-lock.json and would print an error if it wasn't there."

Além disso, a documentação oficial do npm diz o mesmo: [package-lock.json](https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json):

"This file is intended to be committed into source repositories, and serves various purposes."

2024-12-17 15:38 UTC, diverintech commented on src/assets/i18n/pt.json
Obrigada pelas sugestões @fc46581.  Vou alterar no próximo commit 👍

2024-12-17 15:38 UTC, diverintech commented on src/app/pages/about/about.component.scss
@fc46581 mas não chegas a ver a 3ª frase? A mim aparecem as três, depois pára e começa do início porque só tenho 3 frases adicionadas.

2024-12-17 15:38 UTC, diverintech commented on src/app/app.config.ts
> +    ), provideAnimationsAsync(),
Thanks, bom olho 👍 . No futuro quero implementar uma regra que ao fazer push verifica se a indentação está correcta.

2024-12-17 15:38 UTC, diverintech commented on src/app/dialog/math-quiz/math-quiz.component.ts
> +  public userAnswer!: number | null; // Stores the user's answer; allows null for resetting the input field.
Hi. Inicialmente, utilizei o ! para evitar a inicializarão da variável, mas vou alterar para `public userAnswer: number | null = null` para tornar a lógica mais clara e segura.

2024-12-17 16:11 UTC, merged